### ISSUE TITLE
Swdc-vscode-100-days-of-code crashing Extension Host

### ISSUE THREAD

**Issue by pawarashish564** [swdotcom/swdc-vscode-100-days-of-code#8]
I don't know whats the actual reason for this. but Since last two days. I am getting error message 
> Extension host terminated unexpectedly

When I looked into the developer tools It says 
```
[Extension Host] (node:5800) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token  in JSON at position 0
	at JSON.parse (<anonymous>)
	at getSummaryObject (c:\Users\Pawar\.vscode\extensions\softwaredotcom.swdc-100-days-of-code-1.0.1\out\utils\SummaryUtil.js:203:17)
	at Object.reevaluateSummary (c:\Users\Pawar\.vscode\extensions\softwaredotcom.swdc-100-days-of-code-1.0.1\out\utils\SummaryUtil.js:93:19)
	at c:\Users\Pawar\.vscode\extensions\softwaredotcom.swdc-100-days-of-code-1.0.1\out\utils\LogsUtil.js:283:23
	at Generator.next (<anonymous>)
	at fulfilled (c:\Users\Pawar\.vscode\extensions\softwaredotcom.swdc-100-days-of-code-1.0.1\out\utils\LogsUtil.js:5:58)
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

Please look into this issue. Btw I'm big Fan of the extension. Let me know if you have any fixes

**Comment by brettmstevens7** [comment]
Thanks @pawarashish564. We're on it.

**Comment by pawarashish564** [comment]
thanks !
Also consider this. When I download to last stable version still its crashing the extension host.
```
(node:11888) UnhandledPromiseRejectionWarning: TypeError: c.getText is not a function
	at l.getFileParams (c:\Users\Pawar\.vscode\extensions\softwaredotcom.swdc-vscode-2.2.37\dist\extension.js:3:88443)
	at l.<anonymous> (c:\Users\Pawar\.vscode\extensions\softwaredotcom.swdc-vscode-2.2.37\dist\extension.js:3:87216)
	at Generator.next (<anonymous>)
	at o (c:\Users\Pawar\.vscode\extensions\softwaredotcom.swdc-vscode-2.2.37\dist\extension.js:3:83859)
```

**Comment by pawarashish564** [comment]
Thanks Please look into this issue.

**Comment by brettmstevens7** [comment]
@pawarashish564 the changes are in and this will be pushed to the marketplace tomorrow morning Pacific time. [Here's the VSIX](https://github.com/swdotcom/swdc-vscode-100-days-of-code/blob/develop/swdc-100-days-of-code-0.1.3.vsix).

Also, please make sure you upgrade Code Time to 2.2.42 or above. We had issues on 2.2.38 and 2.2.39.

**Comment by pawarashish564** [comment]
Ok I'll update both of extensions tomorrow morning.

**Comment by pawarashish564** [comment]
Thanks @brettmstevens7

**Comment by brettmstevens7** [comment]
@pawarashish564 1.0.2 is now available

**Comment by pawarashish564** [comment]
IDK what happened but I updated CodeTime to 2.2.46 and 100DaysOfCode to 1.0.2 but Still its crashing Extension host.

**Comment by brettmstevens7** [comment]
@pawarashish564 can you paste the exception you see in your console?

**Comment by pawarashish564** [comment]
There are 18 Error showing in debugger
Last one is this.

```c:\Users\Pawar\.vscode\extensions\softwaredotcom.swdc-100-days-of-code-1.0.2\out\utils\SummaryUtil.js:181
    const totalLanguages = currLanguages.concat(newLanguages);
                                         ^

[TypeError: Cannot read property 'concat' of undefined
	at Object.updateSummaryLanguages (c:\Users\Pawar\.vscode\extensions\softwaredotcom.swdc-100-days-of-code-1.0.2\out\utils\SummaryUtil.js:181:42)
	at Object.checkLanguageMilestonesAchieved (c:\Users\Pawar\.vscode\extensions\softwaredotcom.swdc-100-days-of-code-1.0.2\out\utils\MilestonesUtil.js:211:19)
	at Timeout._onTimeout (c:\Users\Pawar\.vscode\extensions\softwaredotcom.swdc-100-days-of-code-1.0.2\out\extension.js:99:34)
	at listOnTimeout (internal/timers.js:531:17)
	at processTimers (internal/timers.js:475:7)]

```

**Comment by pawarashish564** [comment]
thanks for reopening @brettmstevens7 . I have disable 100_days_of_code then code time is working fine.

**Comment by brettmstevens7** [comment]
@pawarashish564 I just pushed `v1.0.3` to the marketplace with that fix. Can you let me know if you see any other errors in your console?

**Comment by pawarashish564** [comment]
### See this.

![image](https://user-images.githubusercontent.com/29516182/90119876-c25ddf00-dd77-11ea-963e-3e1c24dd99a2.png)

**Comment by pawarashish564** [comment]
Any updates ?

**Comment by pawarashish564** [comment]
My Bad it still crashing
```
c:\Users\Pawar\.vscode\extensions\softwaredotcom.swdc-100-days-of-code-1.0.3\out\utils\SummaryUtil.js:182
    const totalLanguages = currLanguages.concat(newLanguages);
                                         ^

[TypeError: Cannot read property 'concat' of undefined
	at Object.updateSummaryLanguages (c:\Users\Pawar\.vscode\extensions\softwaredotcom.swdc-100-days-of-code-1.0.3\out\utils\SummaryUtil.js:182:42)
	at Object.checkLanguageMilestonesAchieved (c:\Users\Pawar\.vscode\extensions\softwaredotcom.swdc-100-days-of-code-1.0.3\out\utils\MilestonesUtil.js:211:19)
	at Timeout._onTimeout (c:\Users\Pawar\.vscode\extensions\softwaredotcom.swdc-100-days-of-code-1.0.3\out\extension.js:99:34)
	at listOnTimeout (internal/timers.js:531:17)
	at processTimers (internal/timers.js:475:7)]

```

**Comment by brettmstevens7** [comment]
@pawarashish564 updated in v1.0.4.

**Comment by pawarashish564** [comment]
OHH GOD not this again . I'm sorry but After working for about 15-20 minutes . Extension host crashed again.
```
c:\Users\Pawar\.vscode\extensions\softwaredotcom.swdc-100-days-of-code-1.0.4\out\utils\SummaryUtil.js:182
    const totalLanguages = currLanguages.concat(newLanguages);
                                         ^

[TypeError: Cannot read property 'concat' of undefined
	at Object.updateSummaryLanguages (c:\Users\Pawar\.vscode\extensions\softwaredotcom.swdc-100-days-of-code-1.0.4\out\utils\SummaryUtil.js:182:42)
	at Object.checkLanguageMilestonesAchieved (c:\Users\Pawar\.vscode\extensions\softwaredotcom.swdc-100-days-of-code-1.0.4\out\utils\MilestonesUtil.js:211:19)
	at Timeout._onTimeout (c:\Users\Pawar\.vscode\extensions\softwaredotcom.swdc-100-days-of-code-1.0.4\out\extension.js:99:34)
	at listOnTimeout (internal/timers.js:531:17)
	at processTimers (internal/timers.js:475:7)]

```

**Comment by pawarashish564** [comment]
any updates @brettmstevens7

**Comment by brettmstevens7** [comment]
@pawarashish564 can you try v1.0.6? @shreyshah33 found the issue.

**Comment by pawarashish564** [comment]
Yes I tried v1.0.6 It is working as intended . Thank you
